### ISSUE TITLE
MooTools 1.3

### ISSUE THREAD

**Issue by theiviaxx** [creaven/miftree#7]
Not really an issue, just wondering if you're working on porting to 1.3?

**Comment by ghost** [comment]
The initialization of the Mif.Tree class (version 1.2.6.3) throws an error ("item is not a constructor") when used with mootools core 1.3

**Comment by CNSKnight** [comment]
just remove all the 'new's in implements:[new Events, ...]

**Comment by SunboX** [comment]
Please make it 1.3 (no-compat) compatiple. Should just be a find & replace ... less function calls == more speed

**Comment by YuccaOne** [comment]
I remove all "new" in implements, and I have two errors again :
- Drag is not defined (Mif.Tree.Drag = new Class({Implements: [Events, Options],>Extends: Drag<,....)
- this.setOptions is not a function ( Mif.Tree = new Class({ ... initialize: function(options){>this.setOptions(options);<....).

I test with the v. 1.2.6.4 of Mif and 1.3.2 of Mootools for just tree select event demo.

**Comment by kalleth** [comment]
I've made a [pull request](https://github.com/creaven/miftree/pull/10) that should make the Core stuff compatible with mootools 1.3 by following the guide on changed API here: https://github.com/mootools/mootools-core/wiki/Upgrade-from-1.2-to-1.3.

Should be about at my copy of the repo too.
